apiVersion: v1
kind: Service
metadata:
  name: wordpress-service
  labels:
    app: wordpress
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30001
  selector:
    app: wordpress
  type: NodePort