apiVersion: v1
kind: pod
metadata:
  name: mysql-volume
spec:
  containers:
  - image: mysql
    name: mysql
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data
    env:
      - name: MYSQL_ROOT_PASSWORD
        value: password
      - name: MYSQL_DATABASE
        value: easytraining
      - name: MYSQL_USER
        value: easy
      - name: MYSQL_PASSWORD 
        value: easy
  volumes:
   - name: mysql-data
     persistentVolumeClaim:
       claimName: pvc
        